import {
  Sparkles, Mail, Image as ImageIcon, AudioLines, Moon,
  PawPrint, Stethoscope, BadgeCheck, Gift, KeyRound,
  BookOpen, ListChecks,
} from "lucide-react";

// 10 personal rooms + 2 shared rooms
export const ROOMS = [
  {
    key: "appreciation",
    title: "Appreciation Garden",
    eyebrow: "APPRECIATION GARDEN",
    icon: Sparkles,
    world: "personal",
    hero: { my: "A garden of things noticed.", buddy: "Plant something they don't see in themselves." },
    sub:  { my: "Each card was placed here, on purpose, by someone who pays attention.",
            buddy: "Small noticings. The things only you would write." },
    accent: "garden",
  },
  {
    key: "letters",
    title: "Letters",
    eyebrow: "LETTERS",
    icon: Mail,
    world: "personal",
    hero: { my: "A small stack of pages, for whenever.", buddy: "Write a letter they can open later." },
    sub:  { my: "Open the envelope when you'd like. None of these expire.",
            buddy: "Write slowly. Leave the date open." },
    accent: "letters",
  },
  {
    key: "memories",
    title: "Memories",
    eyebrow: "MEMORIES",
    icon: ImageIcon,
    world: "personal",
    hero: { my: "Small things, kept on purpose.", buddy: "Save something small and ordinary." },
    sub:  { my: "Tiny moments. Not perfect ones. Just the ones worth keeping.",
            buddy: "A photo, a sentence, a date. That's enough." },
    accent: "memories",
  },
  {
    key: "butterfly_lounge",
    title: "Butterfly Lounge",
    eyebrow: "BUTTERFLY LOUNGE",
    icon: AudioLines,
    world: "personal",
    hero: { my: "A voice note, when you want one.", buddy: "Record a voice note. They'll keep it." },
    sub:  { my: "Soft volume. No urgency. You can stop it whenever. It will be here when you come back.",
            buddy: "Speak slowly. Pauses are allowed." },
    accent: "lounge",
  },
  {
    key: "good_night",
    title: "Good Night",
    eyebrow: "GOOD NIGHT",
    icon: Moon,
    world: "personal",
    hero: { my: "Rest now.", buddy: "Leave a small good-night." },
    sub:  { my: "The day did its best. You did your best. Whatever you didn't finish — it will keep until morning.",
            buddy: "A few lines. A small lullaby." },
    accent: "night",
  },
  {
    key: "dog_cafe",
    title: "Dog Café",
    eyebrow: "DOG CAFÉ",
    icon: PawPrint,
    world: "personal",
    hero: { my: "A small, warm corner with paws.", buddy: "Drop something soft and silly." },
    sub:  { my: "Photographs, ordinary stories, a small order of joy.",
            buddy: "A picture, a name, a tiny memory." },
    accent: "cafe",
  },
  {
    key: "doctor_corner",
    title: "Doctor's Corner",
    eyebrow: "DOCTOR'S CORNER",
    icon: Stethoscope,
    world: "personal",
    hero: { my: "A small clinic of kind reminders.", buddy: "Prescribe rest. Prescribe water." },
    sub:  { my: "No urgency. Open when you need a small, careful note.",
            buddy: "Notes only you would write, in the voice only you have." },
    accent: "doctor",
  },
  {
    key: "achievements",
    title: "Achievements",
    eyebrow: "ACHIEVEMENTS",
    icon: BadgeCheck,
    world: "personal",
    hero: { my: "Awards, conferred by the committee of one.", buddy: "Confer a tiny, deeply specific badge." },
    sub:  { my: "Each badge is hand-pressed. None of them expire. All were earned without you noticing.",
            buddy: "It can be ridiculous. It should be specific." },
    accent: "achievements",
  },
  {
    key: "surprises",
    title: "Surprises",
    eyebrow: "SURPRISES",
    icon: Gift,
    world: "personal",
    hero: { my: "Sealed, for later.", buddy: "Leave a sealed surprise." },
    sub:  { my: "Open them whenever. Some are timed to open themselves.",
            buddy: "Set a date or unlock it later. Or leave it for any day." },
    accent: "surprises",
  },
  {
    key: "secret_room",
    title: "Secret Room",
    eyebrow: "SECRET ROOM",
    icon: KeyRound,
    world: "personal",
    hero: { my: "A room with the door closed.", buddy: "Leave something only they will find." },
    sub:  { my: "Quiet, private notes. Only the two of you ever see this.",
            buddy: "The very small, very private things." },
    accent: "secret",
  },
  // ----- shared -----
  {
    key: "shared_journal",
    title: "Shared Journal",
    eyebrow: "SHARED JOURNAL",
    icon: BookOpen,
    world: "shared",
    hero: { shared: "A page you write together." },
    sub:  { shared: "Both of you can write here. Days, half-sentences, ordinary thoughts." },
    accent: "journal",
  },
  {
    key: "bucket_list",
    title: "Bucket List",
    eyebrow: "BUCKET LIST",
    icon: ListChecks,
    world: "shared",
    hero: { shared: "A small list of someday." },
    sub:  { shared: "Add things. Cross them off when they happen." },
    accent: "bucket",
  },
];

export const ROOM_MAP = Object.fromEntries(ROOMS.map((r) => [r.key, r]));

export const PERSONAL_ROOMS = ROOMS.filter((r) => r.world === "personal");
export const SHARED_ROOMS = ROOMS.filter((r) => r.world === "shared");
